export const ENDPOINT = `http://localhost:5000`;
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const USER_LOUGOUT_SUCCESS = "USER_LOUGOUT_SUCCESS";
export const USER_LOUGOUT_FAILURE = "USER_LOUGOUT_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const POST_TWEET_REQUEST = "POST_TWEET_REQUEST";
export const POST_TWEET_SUCCESS = "POST_TWEET_SUCCESS";
export const POST_TWEET_FAILURE = "POST_TWEET_FAILURE";

export const FETCH_TWEETS_REQUEST = "FETCH_TWEETS_REQUEST";
export const FETCH_TWEETS_SUCCESS = "FETCH_TWEETS_SUCCESS";
export const FETCH_TWEETS_FAILURE = "FETCH_TWEETS_FAILURE";

export const REMOVE_TWEET_REQUEST = "REMOVE_TWEET_REQUEST";
export const REMOVE_TWEET_SUCCESS = "REMOVE_TWEET_SUCCESS";
export const REMOVE_TWEET_FAILURE = "REMOVE_TWEET_FAILURE";

export const EDIT_TWEET_REQUEST = "EDIT_TWEET_REQUEST";
export const EDIT_TWEET_SUCCESS = "EDIT_TWEET_SUCCESS";
export const EDIT_TWEET_FAILURE = "EDIT_TWEET_FAILURE";

export const FETCH_USER_DATA_REQUEST = "FETCH_USER_DATA_REQUEST";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILURE = "FETCH_USER_DATA_FAILURE";

export const FETCH_TWEETS_BY_USERID_REQUEST = "FETCH_TWEETS_BY_USERID_REQUEST";
export const FETCH_TWEETS_BY_USERID_SUCCESS = "FETCH_TWEETS_BY_USERID_SUCCESS";
export const FETCH_TWEETS_BY_USERID_FAILURE = "FETCH_TWEETS_BY_USERID_FAILURE";

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE";

export const FETCH_COMMENT_BY_USER_REQUEST = "POST_COMMENT_REQUEST";
export const FETCH_COMMENT_BY_USER_SUCCESS = "POST_COMMENT_SUCCESS";
export const FETCH_COMMENT_BY_USER_FAILURE = "FETCH_COMMENT_BY_USER_FAILURE";

export const TOGGLE_LIKE_TWEET_SUCCESS = "TOGGLE_LIKE_TWEET_SUCCESS";
export const LIKE_TWEET_FAILURE = "LIKE_TWEET_FAILURE";

export const FETCH_TWEETS_BY_ID_REQUEST = "FETCH_TWEETS_BY_ID_REQUEST";
export const FETCH_TWEETS_BY_ID_SUCCESS = "FETCH_TWEETS_BY_ID_SUCCESS";
export const FETCH_TWEETS_BY_ID_FAILURE = "FETCH_TWEETS_BY_ID_FAILURE";

export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE";

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAILURE = "FETCH_PROFILE_FAILURE";

export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILURE = "FETCH_ALL_USERS_FAILURE";
